name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run manually
  workflow_dispatch:
  # Run on push to main/master
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

          # 📅 Full year calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # ⭐ Stargazers
          plugin_stargazers: yes
